### ISSUE TITLE
Cant download from syosetu.

### ISSUE THREAD

**Issue by usergitHub90** [setsumi/Syosetu-Downloader-plus#18]
Got error messages download from syosetu site

07/05/2024 14:11:25 System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Syousetsu.Methods.GetTotalChapters(HtmlDocument doc, Constants details)
   at syosetuDownloader.MainWindow.<>c__DisplayClass22_0.<Download>b__0()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at syosetuDownloader.MainWindow.Download()
   at syosetuDownloader.MainWindow.DownloadBegin(String link, String start, String end)

![error](https://github.com/setsumi/Syosetu-Downloader-plus/assets/155384586/ac836750-b9a9-4610-b769-a073b7614689)

**Comment by Rase10** [comment]
Yeah, same here

**Comment by setsumi** [comment]
Fixed this.
