### ISSUE TITLE
Problem when trying to download! (v2.4.0-plus26)

### ISSUE THREAD

**Issue by Rase10** [setsumi/Syosetu-Downloader-plus#22]
Can I ask why is this happening?

![image](https://github.com/user-attachments/assets/fa555f19-60fa-4b4e-bab2-4599e05c9bac)

11/1/2024 9:53:45 AM System.IO.DirectoryNotFoundException: Could not find a part of the path 'F:\WBNVL\Syosetu-Downloader-v2.4.0-plus26\_HISTORY_\n2112gv.xml'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Xml.XmlDocument.Save(String filename)
   at Syousetsu.History.SaveFile(Item item, String file)
   at Syousetsu.Methods.<>c__DisplayClass4_0.<AddDownloadJob>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by setsumi** [comment]
Reproduced, will look into it.
Meanwhile as a temporary workaround try manually creating folder `_HISTORY_` beside the syosetuDownloader.exe like this:
![image](https://github.com/user-attachments/assets/a1d150bd-2cb2-4ca5-b95c-47a214b9fbba)
